site_name: YUEN

theme:
  favicon: assets/favicon.png
  name: material
  logo: assets/android-chrome-192x192.png
  palette:
    
  # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
nav:
  - 'Menu': index.md
  - '今日の熟語': 今日の熟語/knojyuku.md
  - 'Kanji' :
    - '漢字' : Kanji/kanji.md
    - 'ことわざ' : Kanji/kotowaza.md
    - '索引' : Kanji/sakuin.md

  - 'Anglais' : 
    - 'Cours(英)' : Anglais/CoursAngl.md
    - 'Voca(全)' : Anglais/voca.md

  - 'Allemand' : 
    - 'Voca(独)' : Allemand/vocaall.md

  - 'Hist-Geo' : 
    - 'Hist-Géo' : Hist/Hist.md

  - 'Science' :
    - 'SVT' : 
      - 'Thème 1' : SVT/SVTth1.md   
      - 'Thème 2' : SVT/SVTth2.md
    - 'Physique-chimie' : 
      - 'Thème 1' : PHYS/PHYSth1.md   
      - 'Thème 2' : PHYS/PHYSth2.md
    - 'Maths' : Maths/maths.md

  - '国語' : Kokugo/kokugo.md

  - 'Emploi du temps (3èmeD)' : Emploi_du_temps.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.arithmatex:
      generic: true
  
extra_javascript:
   - javascripts/mathjax.js
   - https://polyfill.io/v3/polyfill.min.js?features=es6
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
