site_name: YUEN

theme:
  favicon: assets/favicon.png
  name: material
  logo: assets/android-chrome-192x192.png
  palette:
    
  # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
nav:
  - 'Menu': index.md

  - 'Maths':  
    - 'Cours': 
      - 'Aires': Maths/maths/#aires-formule
      - 'Volume et surface': Maths/maths/#volume-et-surface-formule
      - 'fonctions': Maths/maths/#fonctions-et-equations
      - 'calculs indiens': Maths/maths/#calculs-indiens
      - 'Symboles mathématiques': Maths/maths/#symboles-mathematiques-avec-ecriture-latex



  - '漢字' :
    - '漢字' : Kanji/kanji.md


  - 'Français' : 
    - 'Se chercher, se construire' : Français/se_chercher.md

  - 'Anglais' : 
    - 'Cours' : Anglais/CoursAngl.md
    - 'Voca' : Anglais/vocaangl.md

  - 'Allemand' : 
    - 'Trad. (texte)' : Allemand/vocaall.md
    - 'Cours' : Allemand/Allemand.md
 
  - 'Histoire-Geo' : 


    - 'Hist' : 
      - 'Theme 0' : H-G/Hist/H_th0.md

  - 'Science' :
    - 'SVT' : 
      - 'Theme 1' : SVT/SVTth1.md   
      - 'Theme 2' : SVT/SVTth2.md
    - 'Physique-chimie' : 
      - 'Theme 1' : PHYS/PHYSth1.md   
      - 'Theme 2' : PHYS/PHYSth2.md

  - '国語' :
      - 'MENU' : Kokugo/kokugo.md
      - '漢字・語句' : Kokugo/漢字・語句.md  
      - '文法' : Kokugo/文法.md
      - '文学的文章の読解' : Kokugo/文学的文章の読解.md
      - '説明的文章の読解' : Kokugo/説明的文章の読解.md
      - '古典' : Kokugo/古典.md

  - 'Voca(全)' : Voca/voca.md

  - 'Quizz' :
    - 'Quiz (sinus)': Maths/questionnaire/mathex.html
    - 'Quiz (plants)' : Quiz/index.html

  - 'Emploi du temps (3emeD)' : Emploi_du_temps.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.arithmatex:
      generic: true
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - search
      

  
    

